development:
  adapter: postgresql
  encoding: unicode
  database: fails_development
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: fails_test
  pool: 5

cucumber:
  <<: *test
